version: '3.8'

services:
  spring-app:
    build: .
    restart: always
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Xmx512m
  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '8080:80'


volumes:
  postgres-data: